initial conversion to swift 3
darrenclark/objc2swift pull request #2
Opened 2017-01-18 13:41 UTC by mingsai

Just giving a quick conversion to Swift3 and unwinding several errors related to conversion.

2017-01-19 00:42 UTC, darrenclark requested changes
This is great, thanks for the interest in this project!

I tried running the tests and it seemed to have crashed (see other comment)

It also appears some of the added code is indented with spaces.  If you're feeling ambitious, it'd be great if they could be converted to tabs (to be consistent with existing code)

2017-01-19 00:42 UTC, darrenclark commented on objc2swift/AST/ASTConverter.swift
> +				return .binaryOperator(op: op[op.endIndex].spelling, lhs: lhs, rhs: rhs)
Looks like something may have broke here, the tests crash here.

2017-01-19 00:42 UTC, darrenclark commented on objc2swift/Clang/Tokens.swift
> +
Maybe this could be moved somewhere lower in the file? After the initializers

2017-02-19 23:43 UTC, mingsai commented on objc2swift/Clang/Tokens.swift
> +
I'll look into it.

2017-02-19 23:44 UTC, mingsai commented on objc2swift/AST/ASTConverter.swift
> +				return .binaryOperator(op: op[op.endIndex].spelling, lhs: lhs, rhs: rhs)
I should have some time tomorrow to review these notes

2025-04-21 13:24 UTC, closed without merging